#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xmodmap ~/.Xmodmap;

xsetroot -cursor_name left_ptr &

#pkill -USR1 -x sxhkd

# picom &

$HOME/.config/polybar/launch.sh
# /etc/polybar/launch.sh

#spotify &
#wmctrl -r Spotify -t 7
#bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"

bspc config border_width       5
bspc config window_gap         8
#bspc config focused_border_color "#65af91"
#bspc config focused_border_color "#ff8787"
bspc config focused_border_color "#ff4949"
bspc config split_ratio          0.52
#bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Matplotlib state=floating
#bspc rule -a Anki desktop='^6'
bspc rule -a Zathura state=tiled
#bspc rule -a spotify desktop='^9' state=tiled


xrandr --output eDP1 --scale 0.8x0.8
xrandr --output DP1 --scale 1x1.20


xset r rate 175 50 # reducir delay de teclas
setxkbmap -option caps:swapescape



#que workspaces quiero en cada monitor

#bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

bspc wm -O DP1 eDP1





feh --bg-fill ~/media/Pictures/bosque_sur.jpg

